

name: Deploy to AWS Beanstalk

on:
  push:
    branches: [ "master" ]

env:
  AWS_REGION: us-east-1                 


jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t faubsam20/react-test -f Dockerfile.dev
      - run: docker run -e CI=true faubsam20/react-test npm test
      
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git'
        
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: docker-react
          environment_name: Docker-react-env
          existing_bucket_name: bucket
          region: us-east-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
          
